<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      //果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法
      const p1 = new Promise((resolve, reject) => {
        resolve("hello");
      })
        .then((result) => result)
        .catch((e) => e);

      const p2 = new Promise((resolve, reject) => {
        throw new Error("报错了");
      })
        .then((result) => result)
        .catch((e) => e);

      Promise.all([p1, p2])
        .then((result) => console.log(result))
        .catch((e) => console.log(e));
      // ["hello", Error: 报错了]
    </script>
  </body>
</html>
